### ISSUE TITLE
Docker Image size too large

### ISSUE THREAD

**Issue by howawong** [g0vhk-io/ae-waiting-time-dashboard#1]
![image](https://user-images.githubusercontent.com/760880/57565322-7858b180-73ee-11e9-84e8-ed23b64dc79f.png)

https://hub.docker.com/r/g0vhk/ae-waiting-time-dashboards/tags
Please optimize it with multi-stage Dockerfile

**Comment by gaplo917** [comment]
@howawong if it is a pure static web app, you should use [nginx docker image](https://hub.docker.com/_/nginx?tab=tags) to serve. Then no optimizations has to be taken.

P.S. I saw `server.js` only serving the static files

**Comment by howawong** [comment]
Probably, a pull request is welcomed. Thanks!

**Comment by howawong** [comment]
Seems #2 solved the problem, closing this issue.
